version: '3'

services:
  cluster:
    build: ./clusterdir
    ports:
      - "8080:8080"
    command: tail -f /dev/null

  client1:
    build: ./clientdir
    command: tail -f /dev/null

  client2:
    build: ./clientdir
    command: tail -f /dev/null

  consumer1:
    build: ./consumerdir
    command: tail -f /dev/null

  consumer2:
    build: ./consumerdir
    command: tail -f /dev/null
